// flow-typed signature: f9e90d354ff7d7adfbc61d7bb7b5e534
// flow-typed version: <<STUB>>/react-simple-maps_v^0.8.3/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-simple-maps'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "react-simple-maps" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "react-simple-maps/lib/Annotation" {
  declare module.exports: any;
}

declare module "react-simple-maps/lib/ComposableMap" {
  declare module.exports: any;
}

declare module "react-simple-maps/lib/Geographies" {
  declare module.exports: any;
}

declare module "react-simple-maps/lib/Geography" {
  declare module.exports: any;
}

declare module "react-simple-maps/lib/Graticule" {
  declare module.exports: any;
}

declare module "react-simple-maps/lib/index" {
  declare module.exports: any;
}

declare module "react-simple-maps/lib/Marker" {
  declare module.exports: any;
}

declare module "react-simple-maps/lib/Markers" {
  declare module.exports: any;
}

declare module "react-simple-maps/lib/projectionConfig" {
  declare module.exports: any;
}

declare module "react-simple-maps/lib/projections" {
  declare module.exports: any;
}

declare module "react-simple-maps/lib/utils" {
  declare module.exports: any;
}

declare module "react-simple-maps/lib/ZoomableGroup" {
  declare module.exports: any;
}

declare module "react-simple-maps/src/Annotation" {
  declare module.exports: any;
}

declare module "react-simple-maps/src/ComposableMap" {
  declare module.exports: any;
}

declare module "react-simple-maps/src/Geographies" {
  declare module.exports: any;
}

declare module "react-simple-maps/src/Geography" {
  declare module.exports: any;
}

declare module "react-simple-maps/src/Graticule" {
  declare module.exports: any;
}

declare module "react-simple-maps/src/index" {
  declare module.exports: any;
}

declare module "react-simple-maps/src/Marker" {
  declare module.exports: any;
}

declare module "react-simple-maps/src/Markers" {
  declare module.exports: any;
}

declare module "react-simple-maps/src/projectionConfig" {
  declare module.exports: any;
}

declare module "react-simple-maps/src/projections" {
  declare module.exports: any;
}

declare module "react-simple-maps/src/utils" {
  declare module.exports: any;
}

declare module "react-simple-maps/src/ZoomableGroup" {
  declare module.exports: any;
}

declare module "react-simple-maps/tests/utils.spec" {
  declare module.exports: any;
}

// Filename aliases
declare module "react-simple-maps/lib/Annotation.js" {
  declare module.exports: $Exports<"react-simple-maps/lib/Annotation">;
}
declare module "react-simple-maps/lib/ComposableMap.js" {
  declare module.exports: $Exports<"react-simple-maps/lib/ComposableMap">;
}
declare module "react-simple-maps/lib/Geographies.js" {
  declare module.exports: $Exports<"react-simple-maps/lib/Geographies">;
}
declare module "react-simple-maps/lib/Geography.js" {
  declare module.exports: $Exports<"react-simple-maps/lib/Geography">;
}
declare module "react-simple-maps/lib/Graticule.js" {
  declare module.exports: $Exports<"react-simple-maps/lib/Graticule">;
}
declare module "react-simple-maps/lib/index.js" {
  declare module.exports: $Exports<"react-simple-maps/lib/index">;
}
declare module "react-simple-maps/lib/Marker.js" {
  declare module.exports: $Exports<"react-simple-maps/lib/Marker">;
}
declare module "react-simple-maps/lib/Markers.js" {
  declare module.exports: $Exports<"react-simple-maps/lib/Markers">;
}
declare module "react-simple-maps/lib/projectionConfig.js" {
  declare module.exports: $Exports<"react-simple-maps/lib/projectionConfig">;
}
declare module "react-simple-maps/lib/projections.js" {
  declare module.exports: $Exports<"react-simple-maps/lib/projections">;
}
declare module "react-simple-maps/lib/utils.js" {
  declare module.exports: $Exports<"react-simple-maps/lib/utils">;
}
declare module "react-simple-maps/lib/ZoomableGroup.js" {
  declare module.exports: $Exports<"react-simple-maps/lib/ZoomableGroup">;
}
declare module "react-simple-maps/src/Annotation.js" {
  declare module.exports: $Exports<"react-simple-maps/src/Annotation">;
}
declare module "react-simple-maps/src/ComposableMap.js" {
  declare module.exports: $Exports<"react-simple-maps/src/ComposableMap">;
}
declare module "react-simple-maps/src/Geographies.js" {
  declare module.exports: $Exports<"react-simple-maps/src/Geographies">;
}
declare module "react-simple-maps/src/Geography.js" {
  declare module.exports: $Exports<"react-simple-maps/src/Geography">;
}
declare module "react-simple-maps/src/Graticule.js" {
  declare module.exports: $Exports<"react-simple-maps/src/Graticule">;
}
declare module "react-simple-maps/src/index.js" {
  declare module.exports: $Exports<"react-simple-maps/src/index">;
}
declare module "react-simple-maps/src/Marker.js" {
  declare module.exports: $Exports<"react-simple-maps/src/Marker">;
}
declare module "react-simple-maps/src/Markers.js" {
  declare module.exports: $Exports<"react-simple-maps/src/Markers">;
}
declare module "react-simple-maps/src/projectionConfig.js" {
  declare module.exports: $Exports<"react-simple-maps/src/projectionConfig">;
}
declare module "react-simple-maps/src/projections.js" {
  declare module.exports: $Exports<"react-simple-maps/src/projections">;
}
declare module "react-simple-maps/src/utils.js" {
  declare module.exports: $Exports<"react-simple-maps/src/utils">;
}
declare module "react-simple-maps/src/ZoomableGroup.js" {
  declare module.exports: $Exports<"react-simple-maps/src/ZoomableGroup">;
}
declare module "react-simple-maps/tests/utils.spec.js" {
  declare module.exports: $Exports<"react-simple-maps/tests/utils.spec">;
}
