// flow-typed signature: a92a4a04501c42b4f2754708b99b725e
// flow-typed version: <<STUB>>/redux-tooltip_v^0.7.2/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-tooltip'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-tooltip' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-tooltip/build/content.bundle' {
  declare module.exports: any;
}

declare module 'redux-tooltip/build/delay.bundle' {
  declare module.exports: any;
}

declare module 'redux-tooltip/build/keep.bundle' {
  declare module.exports: any;
}

declare module 'redux-tooltip/build/multiple.bundle' {
  declare module.exports: any;
}

declare module 'redux-tooltip/build/origin.bundle' {
  declare module.exports: any;
}

declare module 'redux-tooltip/build/place.bundle' {
  declare module.exports: any;
}

declare module 'redux-tooltip/build/remote.bundle' {
  declare module.exports: any;
}

declare module 'redux-tooltip/build/shared' {
  declare module.exports: any;
}

declare module 'redux-tooltip/build/simple.bundle' {
  declare module.exports: any;
}

declare module 'redux-tooltip/build/style.bundle' {
  declare module.exports: any;
}

declare module 'redux-tooltip/karma.conf' {
  declare module.exports: any;
}

declare module 'redux-tooltip/lib/actions' {
  declare module.exports: any;
}

declare module 'redux-tooltip/lib/index' {
  declare module.exports: any;
}

declare module 'redux-tooltip/lib/middleware' {
  declare module.exports: any;
}

declare module 'redux-tooltip/lib/origin' {
  declare module.exports: any;
}

declare module 'redux-tooltip/lib/reducer' {
  declare module.exports: any;
}

declare module 'redux-tooltip/lib/styles' {
  declare module.exports: any;
}

declare module 'redux-tooltip/lib/themes' {
  declare module.exports: any;
}

declare module 'redux-tooltip/lib/tooltip' {
  declare module.exports: any;
}

declare module 'redux-tooltip/lib/utils' {
  declare module.exports: any;
}

declare module 'redux-tooltip/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-tooltip/build/content.bundle.js' {
  declare module.exports: $Exports<'redux-tooltip/build/content.bundle'>;
}
declare module 'redux-tooltip/build/delay.bundle.js' {
  declare module.exports: $Exports<'redux-tooltip/build/delay.bundle'>;
}
declare module 'redux-tooltip/build/keep.bundle.js' {
  declare module.exports: $Exports<'redux-tooltip/build/keep.bundle'>;
}
declare module 'redux-tooltip/build/multiple.bundle.js' {
  declare module.exports: $Exports<'redux-tooltip/build/multiple.bundle'>;
}
declare module 'redux-tooltip/build/origin.bundle.js' {
  declare module.exports: $Exports<'redux-tooltip/build/origin.bundle'>;
}
declare module 'redux-tooltip/build/place.bundle.js' {
  declare module.exports: $Exports<'redux-tooltip/build/place.bundle'>;
}
declare module 'redux-tooltip/build/remote.bundle.js' {
  declare module.exports: $Exports<'redux-tooltip/build/remote.bundle'>;
}
declare module 'redux-tooltip/build/shared.js' {
  declare module.exports: $Exports<'redux-tooltip/build/shared'>;
}
declare module 'redux-tooltip/build/simple.bundle.js' {
  declare module.exports: $Exports<'redux-tooltip/build/simple.bundle'>;
}
declare module 'redux-tooltip/build/style.bundle.js' {
  declare module.exports: $Exports<'redux-tooltip/build/style.bundle'>;
}
declare module 'redux-tooltip/karma.conf.js' {
  declare module.exports: $Exports<'redux-tooltip/karma.conf'>;
}
declare module 'redux-tooltip/lib/actions.js' {
  declare module.exports: $Exports<'redux-tooltip/lib/actions'>;
}
declare module 'redux-tooltip/lib/index.js' {
  declare module.exports: $Exports<'redux-tooltip/lib/index'>;
}
declare module 'redux-tooltip/lib/middleware.js' {
  declare module.exports: $Exports<'redux-tooltip/lib/middleware'>;
}
declare module 'redux-tooltip/lib/origin.js' {
  declare module.exports: $Exports<'redux-tooltip/lib/origin'>;
}
declare module 'redux-tooltip/lib/reducer.js' {
  declare module.exports: $Exports<'redux-tooltip/lib/reducer'>;
}
declare module 'redux-tooltip/lib/styles.js' {
  declare module.exports: $Exports<'redux-tooltip/lib/styles'>;
}
declare module 'redux-tooltip/lib/themes.js' {
  declare module.exports: $Exports<'redux-tooltip/lib/themes'>;
}
declare module 'redux-tooltip/lib/tooltip.js' {
  declare module.exports: $Exports<'redux-tooltip/lib/tooltip'>;
}
declare module 'redux-tooltip/lib/utils.js' {
  declare module.exports: $Exports<'redux-tooltip/lib/utils'>;
}
declare module 'redux-tooltip/webpack.config.js' {
  declare module.exports: $Exports<'redux-tooltip/webpack.config'>;
}
