// flow-typed signature: 5a964d306f04f98e383e85ea7d11d0dc
// flow-typed version: <<STUB>>/@kevinahuber/redux-tooltip_v^0.7.2/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@kevinahuber/redux-tooltip'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@kevinahuber/redux-tooltip' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@kevinahuber/redux-tooltip/karma.conf' {
  declare module.exports: any;
}

declare module '@kevinahuber/redux-tooltip/lib/actions' {
  declare module.exports: any;
}

declare module '@kevinahuber/redux-tooltip/lib/index' {
  declare module.exports: any;
}

declare module '@kevinahuber/redux-tooltip/lib/middleware' {
  declare module.exports: any;
}

declare module '@kevinahuber/redux-tooltip/lib/origin' {
  declare module.exports: any;
}

declare module '@kevinahuber/redux-tooltip/lib/reducer' {
  declare module.exports: any;
}

declare module '@kevinahuber/redux-tooltip/lib/styles' {
  declare module.exports: any;
}

declare module '@kevinahuber/redux-tooltip/lib/themes' {
  declare module.exports: any;
}

declare module '@kevinahuber/redux-tooltip/lib/tooltip' {
  declare module.exports: any;
}

declare module '@kevinahuber/redux-tooltip/lib/utils' {
  declare module.exports: any;
}

declare module '@kevinahuber/redux-tooltip/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module '@kevinahuber/redux-tooltip/karma.conf.js' {
  declare module.exports: $Exports<'@kevinahuber/redux-tooltip/karma.conf'>;
}
declare module '@kevinahuber/redux-tooltip/lib/actions.js' {
  declare module.exports: $Exports<'@kevinahuber/redux-tooltip/lib/actions'>;
}
declare module '@kevinahuber/redux-tooltip/lib/index.js' {
  declare module.exports: $Exports<'@kevinahuber/redux-tooltip/lib/index'>;
}
declare module '@kevinahuber/redux-tooltip/lib/middleware.js' {
  declare module.exports: $Exports<'@kevinahuber/redux-tooltip/lib/middleware'>;
}
declare module '@kevinahuber/redux-tooltip/lib/origin.js' {
  declare module.exports: $Exports<'@kevinahuber/redux-tooltip/lib/origin'>;
}
declare module '@kevinahuber/redux-tooltip/lib/reducer.js' {
  declare module.exports: $Exports<'@kevinahuber/redux-tooltip/lib/reducer'>;
}
declare module '@kevinahuber/redux-tooltip/lib/styles.js' {
  declare module.exports: $Exports<'@kevinahuber/redux-tooltip/lib/styles'>;
}
declare module '@kevinahuber/redux-tooltip/lib/themes.js' {
  declare module.exports: $Exports<'@kevinahuber/redux-tooltip/lib/themes'>;
}
declare module '@kevinahuber/redux-tooltip/lib/tooltip.js' {
  declare module.exports: $Exports<'@kevinahuber/redux-tooltip/lib/tooltip'>;
}
declare module '@kevinahuber/redux-tooltip/lib/utils.js' {
  declare module.exports: $Exports<'@kevinahuber/redux-tooltip/lib/utils'>;
}
declare module '@kevinahuber/redux-tooltip/webpack.config.js' {
  declare module.exports: $Exports<'@kevinahuber/redux-tooltip/webpack.config'>;
}
