export {default as Categories} from './Categories'
export {default as Comparisons} from './Comparisons'
export {default as Controls} from './Controls'
export {default as Footer} from './Footer'
export {default as Header} from './Header'
export {default as Map} from './Map'
